apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: health-risk-mlops
data:
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  DRIFT_THRESHOLD: "0.5"
  SERVER_PORT: "5050"
  MIN_CLIENTS: "2"
  NUM_ROUNDS: "10"
  MODEL_VERSION: "latest"

